services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=kpi_monitor
      - LANG=C
      - LC_ALL=C
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./docker/timescaledb/data:/var/lib/postgresql/data
    command: postgres -c 'client_encoding=UTF8'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kpi_monitor"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
